language: r
sudo: required

warnings_are_errors: false

os:
  - linux
  - osx
  
compiler:
  - gcc
  - clang
  
apt_packages: 
 - libgsl0-dev
 
r_github_packages:
 - jimhester/covr
 
after_success:
 - Rscript -e 'library(covr);codecov()'
 
r_check_args: "--as-cran"

