language: r
sudo: required

warnings_are_errors: true

apt_packages: 
 - libgsl0-dev
 
r_github_packages:
 - jimhester/covr
 
after_success:
 - Rscript -e 'library(covr);package_coverage(quiet = FALSE);coveralls()'
 
r_check_args: "--as-cran"

